apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom: # pega todas as variáveis definidas em configmap
        - configMapRef:
            name: db-configmap
      # env: #define unicamente partir do ConfigMap
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_ROOT_PASSWORD

      # env: #definido variável diretamente
      #   - name: "MYSQL_ROOT_PASSWORD"
      #     value: "q1w2e3r4"
